# Generated by scripts/formula.sh for v0.1.0. Do not hand-edit: the next
# release overwrites this file, and hand edits are what make a tap lie.
class Wd < Formula
  desc "An autonomous software factory: roadmap to goal to shipped work"
  homepage "https://github.com/mkhanal/work-director"
  version "v0.1.0"
  license "MIT"

  def install
    if OS.mac? && Hardware::CPU.arm?
      url "https://github.com/mkhanal/work-director/releases/download/v0.1.0/wd-darwin-arm64.tar.gz"
      sha256 "555426f8074f4b08890c8ae6d18d5e23a60ce25167779e6619f2e7d9425a92fa"
    end
    if OS.mac? && Hardware::CPU.intel?
      url "https://github.com/mkhanal/work-director/releases/download/v0.1.0/wd-darwin-amd64.tar.gz"
      sha256 "9a20873c14401939866bb3d22f9c757bbbe2b20211452c77ad01721d3f06e0ff"
    end
    if OS.linux && Hardware::CPU.is_64_bit? && Hardware::CPU.intel?
      url "https://github.com/mkhanal/work-director/releases/download/v0.1.0/wd-linux-amd64.tar.gz"
      sha256 "de79d8534f0d6b95c1d6684c13675e4cf2353db03c62f4cc7e707c18f84fbd8d"
    end
    if OS.linux && Hardware::CPU.is_64_bit? && Hardware::CPU.arm? && !Hardware::CPU.intel?
      url "https://github.com/mkhanal/work-director/releases/download/v0.1.0/wd-linux-arm64.tar.gz"
      sha256 "cd829f315d2a3804a742ab5543f0b06fce3a155775a5ff5006937931afba1e42"
    end

    bin.install "wd"
  end

  def caveats
    <<~EOS
      wd keeps its ledger in ~/.work-director and needs no server. Run:
        wd doctor     # which runner CLIs are detected
        wd serve      # the web UI and JSON API
    EOS
  end

  test do
    assert_match "wd", shell_output("#{bin}/wd --version")
  end
end
