#!/usr/bin/env bash
# Generate the Homebrew formula for a published release from the assets that
# release actually shipped, so its version, urls and shasums cannot drift from
# what a person downloads.
#
#   VERSION=v1.2.0 scripts/formula.sh          # reads dist/*.sha256
#   VERSION=v1.2.0 REPO_DIR=/path/to/repo scripts/formula.sh
#
# Homebrew cannot fetch one url for several architectures in a formula without
# conditional blocks, so each platform/arch gets its own stanza and each carries
# its own sha256 from the release. There is no build dependency: the release
# ships a compiled binary, and a binary formula that declares Go would make
# everyone install a toolchain they will never use.
set -euo pipefail
cd "$(dirname "$0")/.."

version=${VERSION:-}
[ -n "$version" ] || { echo "formula: set VERSION to the tag being released" >&2; exit 1; }
repo=${REPO:-mkhanal/work-director}

# shasum prints "<hash>  <file>" (two spaces); the formula wants the hash on
# its own line per platform.
hash_for() {
  local asset="wd-$1-$2.tar.gz"
  local f="dist/$asset.sha256"
  [ -f "$f" ] || { echo "formula: missing $f — run scripts/build.sh first" >&2; exit 1; }
  awk '{print $1}' "$f"
}

# stanza emits one `if` arm: a url and the sha256 of exactly that asset.
stanza() {
  local os=$1 arch=$2 cond=$3
  local asset="wd-$os-$arch.tar.gz"
  cat <<RUBY
    if ${cond}
      url "https://github.com/${repo}/releases/download/${version}/${asset}"
      sha256 "$(hash_for "$os" "$arch")"
    end
RUBY
}

{
  cat <<HEAD
# Generated by scripts/formula.sh for ${version}. Do not hand-edit: the next
# release overwrites this file, and hand edits are what make a tap lie.
class Wd < Formula
  desc "An autonomous software factory: roadmap to goal to shipped work"
  homepage "https://github.com/${repo}"
  version "${version}"
  license "MIT"

  def install
HEAD

  stanza darwin arm64 'OS.mac? && Hardware::CPU.arm?'
  stanza darwin amd64 'OS.mac? && Hardware::CPU.intel?'
  stanza linux  amd64 'OS.linux && Hardware::CPU.is_64_bit? && Hardware::CPU.intel?'
  stanza linux  arm64 'OS.linux && Hardware::CPU.is_64_bit? && Hardware::CPU.arm? && !Hardware::CPU.intel?'

  cat <<'TAIL'

    bin.install "wd"
  end

  def caveats
    <<~EOS
      wd keeps its ledger in ~/.work-director and needs no server. Run:
        wd doctor     # which runner CLIs are detected
        wd serve      # the web UI and JSON API
    EOS
  end

  test do
    assert_match "wd", shell_output("#{bin}/wd --version")
  end
end
TAIL
} > scripts/homebrew/wd.rb

echo "wrote scripts/homebrew/wd.rb for $version"
